export const OPBILLING_SCHEMA = {
  required: [
    'Visit_ID',
    'Patient_ID',
    'Patient_Name',
    'Age',
    'Visit_Date',
    'Doctor_ID',
    'Procedure_Code',
    'Payer_Type',
    'Amount',
    'Consent_Flag'
  ],
  optional: [
    'Bill_ID',
    'Bill_Date',
    'Doctor_Name',
    'Department',
    'Service_Code',
    'Service_Description',
    'Quantity',
    'Unit_Price',
    'Total_Amount',
    'Payment_Status',
    'Payment_Method',
    'Discount_Amount',
    'Tax_Amount',
    'Net_Amount',
    'Currency',
    'Payer',
    'Insurance_Provider',
    'Policy_Number',
    'Authorization_No',
    'Due_Date',
    'Paid_Date',
    'Notes'
  ],
  types: {
    Visit_ID: 'string',
    Patient_ID: 'string',
    Patient_Name: 'string',
    Age: 'number',
    Visit_Date: 'date',
    Doctor_ID: 'string',
    Procedure_Code: 'string',
    Payer_Type: 'string',
    Amount: 'number',
    Consent_Flag: 'string',
    Bill_ID: 'string',
    Bill_Date: 'date',
    Doctor_Name: 'string',
    Department: 'string',
    Service_Code: 'string',
    Service_Description: 'string',
    Quantity: 'number',
    Unit_Price: 'number',
    Total_Amount: 'number',
    Discount_Amount: 'number',
    Tax_Amount: 'number',
    Net_Amount: 'number',
    Payment_Method: 'string',
    Payment_Status: 'string',
    Currency: 'string',
    Payer: 'string',
    Insurance_Provider: 'string',
    Policy_Number: 'string',
    Authorization_No: 'string',
    Due_Date: 'date',
    Paid_Date: 'date',
    Notes: 'string'
  }
};




